# Generated by Django 4.0.4 on 2022-05-09 19:38

from django.db import migrations


def create_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User(login="Vika", email="vika@email.com", password="123456").save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]